package com.example.kakeibo_dev_6.enum

enum class Route {
    EXPENDITURE_ITEM_LIST,
    EDIT_EXPENDITURE,
    PAY_DETAIL,
    CATEGORY_SETTING,
    REPLACE_ORDER_CATEGORY,
    EDIT_CATEGORY,
    EXPENDITURE_ITEM_DETAIL,
    EDIT_EXPENDITURE_WITH_EDIT_CATEGORY
}